<MyWidget>
    cols: 2
    password: password
    Label:
        text: 'User name'
    TextInput:
        multiline: False
        id: username
    Label:
        text: 'password'
    TextInput:
        password: True
        multiline: False
        id: password
    Button:
        text: 'Submit'
        on_press: root.on_submit()
    Button:
        text: 'reset'
        on_press: root.on_reset()